spring.application.name=api.NovaCart.in

spring.datasource.url=jdbc:mysql://localhost:3306/novaCart_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.context-path=/api/v1.0
